# Generated by Django 2.2 on 2022-09-19 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farm_base', '0004_auto_20220919_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='municipality',
            field=models.CharField(max_length=255, null=True, verbose_name='Municipality'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='farm_base.Owner'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='state',
            field=models.CharField(max_length=255, null=True, verbose_name='State'),
        ),
    ]
